name: Super Linter
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  super_linter:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run super-linter
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # LINTER_RULES_PATH: .github/linters
          # LINTER_RULES_PATH: .github/linters
          # LINTER_RULES_PATH: .github/linters
          # LINTER